/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opencv_sample_cube3d_NativeClass */

#ifndef _Included_org_opencv_sample_cube3d_NativeClass
#define _Included_org_opencv_sample_cube3d_NativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opencv_sample_cube3d_NativeClass
 * Method:    EstimatePose
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_org_opencv_sample_cube3d_NativeClass_EstimatePose
  (JNIEnv * env, jobject obj, jlong inputImage);

#ifdef __cplusplus
}
#endif
#endif
